### ISSUE TITLE
youtube-tutorials/2.1 EEG ML classification.ipynb - Fitting into grid search error

### ISSUE THREAD

**Issue by abhishekinnvonix** [talhaanwarch/youtube-tutorials#2]
In last input 

```
clf=LogisticRegression()
gkf=GroupKFold(5)
param_grid = {'classifier__C': [0.1,0.5,0.7, 1,3,5,7]}
pipe=Pipeline([('scaler',StandardScaler()),('classifier',clf)])
gscv=GridSearchCV(pipe,param_grid,cv=gkf,n_jobs=1)
gscv.fit(features_array,label_array,groups=group_array)

```
Error comes in 

`gscv.fit(features_array,label_array,groups=group_array)
`

Error is 

> ValueError: This solver needs samples of at least 2 classes in the data, but the data contains only one class: 0

Please if you can share way out

**Comment by talhaanwarch** [comment]
Hi, please check your labels. look like you have one class only

**Comment by abhishekinnvonix** [comment]
Hi, Sorry I figured it have made both as same labels only..
Thanks for the great tutorial..
